# NumPy 和陣列導向的程式設計

`NumPy` 可以說是 Python 中最最標準的科學計算、數據分析套件。也因為 `NumPy` 的出現, 讓 Python 有了非常好的數據分析基礎, 一直到現在成為數據分析覇主。

In [3]:
import numpy as np

## 1. 陣列導向 101

科學計算一個很核心的概念叫 "array oriented" 的寫法。Array 是 `numpy` 標準的資料結構, 和 list 很像, 但就差了那麼一點點。而這一點點讓我們在計算上是無比的方便。

### 【暖身】 計算平均

某位同學期中考各科成績如下, 請幫他計算成績。

    grades = [77, 85, 56, 90, 66]
    
請計算平均。

In [20]:
s = 0 #sum/個數=average
grades = [77, 85, 56, 90, 66]
for i in grades: #計算有幾個科目:用list走訪 把分數存到s
    s += i # (s = s + i)
#print('average=', s/len(grades)) 
print('average={0:6.2f}, sum = {1}'.format(s/len(grades),s)) #🌟❓
# 格式化輸出到小數點後兩位2f #f=float #0:0f四捨五入 只取整數
# :前面是整數
# .要顯示幾個數字(含小數點、空格 任合符號) if n < mf 會自動忽略n

average= 74.80, sum = 374


### 【示範】陣列導向

In [24]:
grades = [77, 85, 56, 90, 66] #array可以直接運算
arr = np.array(grades)
arr.mean()

74.8

最大值

In [25]:
arr.max()

90

標準差

In [26]:
arr.std()

12.416118556135006

### 【暖身】 換算匯率

假設今天我想查查號稱 Pentax 三公主的 31mm, 43mm, 77mm 三隻 limited 鏡頭在美國賣多少。於是我去 B&H 查了他們的價格分別是:

    prices = [1096.95, 596.95, 896.95]
    
我又查了 Google 匯率 1 美金為 31.71 元。請把三支鏡頭的價格換算為台幣。

In [165]:
prices = [1096.95, 596.95, 896.95]
USD_2_TWD = 31.71
TWD = []
for i in prices:
    twd = i*USD_2_TWD 
    TWD.append(twd) #🌟🌟

In [166]:
TWD

[34784.2845, 18929.2845, 28442.2845]

先不管這實在有夠醜的數字, 我們要記得在科學計算中:

### 儘可能不要使用迴圈

這可能嗎?

### 【示範】陣列換算匯率

In [30]:
prices = [1096.95, 596.95, 896.95]
prices = np.array(prices) #轉成np格式
USD_2_TWD = 31.71
prices*USD_2_TWD

array([34784.2845, 18929.2845, 28442.2845])

哦哦, 傑克, 這太神奇了!

## 2. 其實 array 還有很多功能

### 【練習】 成績計算

一位老師成績這樣算的:

* 平時成績 20%
* 期中考   35%
* 期未考   45%

有位同學

* 平時成績 85 分
* 期中 70 分
* 期末 80 分

這位同學的學期成績是多少?

In [38]:
grades = np.array([85,70,80])
weights = np.array([0.2, 0.35, 0.45])
grades*weights

array([17. , 24.5, 36. ])

這還不是我們要的最終成績啊!

### 【提示】 array 還有很多函數可以用

可以先打入

    weighted_grades.
    
先不要按 `enter` 或 `shift-enter`, 而是按 `tab`...


In [42]:
weighted_grades = grades*weights
weighted_grades.sum()

77.5

### 【技巧】 一行完成成績計算

In [43]:
np.dot(grades, weights) #🌟np.dot點乘積公式

77.5

## 3. 重要的 array 大變身!

我們在數據分析, 常常要改 array 的型式。

### 【練習】 一個 50 個數字的 array

先想辦法、用亂數做出 50 個數字的 array, 叫做 A 好了。

In [67]:
A = np.random.rand(50)
print(A)

[0.29426416 0.88687201 0.00929972 0.79827202 0.93897075 0.90419302
 0.67912763 0.0345746  0.93622183 0.34112978 0.45136977 0.59060073
 0.76892058 0.76470578 0.69199054 0.59803374 0.95219828 0.68597586
 0.32079625 0.58030128 0.01815169 0.07349081 0.65101478 0.75088199
 0.15624646 0.61342987 0.75175776 0.92855132 0.21638928 0.83846159
 0.6141526  0.30037696 0.31821007 0.96347321 0.29602423 0.807761
 0.74888232 0.60662967 0.00880551 0.1184378  0.53995408 0.0574672
 0.98144719 0.54665756 0.09362381 0.39962189 0.10744294 0.5062356
 0.30301847 0.6747559 ]


In [66]:
A[0] #if放在上面同一格 也會是random取出(每次結果不同)

0.28845723473273177

### 【技巧】 檢查 A 的 `shape`

In [52]:
A.shape

(50,)

### 【技巧】 更改 A 的 shape

In [72]:
A.shape = (5, 10) #改成 5 row, 10 col的矩陣(每10比一列)
#多了[], 讀取時要注意
A

array([[0.29426416, 0.88687201, 0.00929972, 0.79827202, 0.93897075,
        0.90419302, 0.67912763, 0.0345746 , 0.93622183, 0.34112978],
       [0.45136977, 0.59060073, 0.76892058, 0.76470578, 0.69199054,
        0.59803374, 0.95219828, 0.68597586, 0.32079625, 0.58030128],
       [0.01815169, 0.07349081, 0.65101478, 0.75088199, 0.15624646,
        0.61342987, 0.75175776, 0.92855132, 0.21638928, 0.83846159],
       [0.6141526 , 0.30037696, 0.31821007, 0.96347321, 0.29602423,
        0.807761  , 0.74888232, 0.60662967, 0.00880551, 0.1184378 ],
       [0.53995408, 0.0574672 , 0.98144719, 0.54665756, 0.09362381,
        0.39962189, 0.10744294, 0.5062356 , 0.30301847, 0.6747559 ]])

In [73]:
A[0] #會變成讀到整row

array([0.29426416, 0.88687201, 0.00929972, 0.79827202, 0.93897075,
       0.90419302, 0.67912763, 0.0345746 , 0.93622183, 0.34112978])

In [75]:
A[0,0] #第一個數值在第0行 第0列 

0.2942641563246251

### 【技巧】 也可以用 `reshape`

但要注意, reshape 並沒有改原來的陣列。

In [76]:
A.reshape(10,5) #跟.shape比 少了=(assign)的動作

array([[0.29426416, 0.88687201, 0.00929972, 0.79827202, 0.93897075],
       [0.90419302, 0.67912763, 0.0345746 , 0.93622183, 0.34112978],
       [0.45136977, 0.59060073, 0.76892058, 0.76470578, 0.69199054],
       [0.59803374, 0.95219828, 0.68597586, 0.32079625, 0.58030128],
       [0.01815169, 0.07349081, 0.65101478, 0.75088199, 0.15624646],
       [0.61342987, 0.75175776, 0.92855132, 0.21638928, 0.83846159],
       [0.6141526 , 0.30037696, 0.31821007, 0.96347321, 0.29602423],
       [0.807761  , 0.74888232, 0.60662967, 0.00880551, 0.1184378 ],
       [0.53995408, 0.0574672 , 0.98144719, 0.54665756, 0.09362381],
       [0.39962189, 0.10744294, 0.5062356 , 0.30301847, 0.6747559 ]])

### 【技巧】 拉平 `ravel`

雖然你想一想就知道可以用 `shape` 或 `reshape` 把多維陣列拉成一維。不過用 `ravel` 很潮。

In [79]:
A.ravel()
# 也可A.reshape(1,50) #拉平成1d array

array([0.29426416, 0.88687201, 0.00929972, 0.79827202, 0.93897075,
       0.90419302, 0.67912763, 0.0345746 , 0.93622183, 0.34112978,
       0.45136977, 0.59060073, 0.76892058, 0.76470578, 0.69199054,
       0.59803374, 0.95219828, 0.68597586, 0.32079625, 0.58030128,
       0.01815169, 0.07349081, 0.65101478, 0.75088199, 0.15624646,
       0.61342987, 0.75175776, 0.92855132, 0.21638928, 0.83846159,
       0.6141526 , 0.30037696, 0.31821007, 0.96347321, 0.29602423,
       0.807761  , 0.74888232, 0.60662967, 0.00880551, 0.1184378 ,
       0.53995408, 0.0574672 , 0.98144719, 0.54665756, 0.09362381,
       0.39962189, 0.10744294, 0.5062356 , 0.30301847, 0.6747559 ])

## 4. 快速 array 生成法

### 【技巧】 都是 0 的 array

In [84]:
np.zeros(10) #在影像處理0=black 常用

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [83]:
np.zeros([3,4]) #用((3,4))也可以

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 【技巧】 都是 1 的 array

In [81]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### 【技巧】單位矩陣

In [86]:
#單位矩陣：斜角都是1, 其餘皆是0
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 【技巧】給定範圍均勻生出 n 個點

In [87]:
x = np.linspace(0,10,100) #均勻地生出0-10的數值 100個
x

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

### 【技巧】`range` 的 array 版

就是 `arange`。

In [88]:
 np.arange(1,10,0.2) #list裡有range; 在陣列裡為arange(同功能) 
#(起始值(0可略), 終止值, 變動方向與量(1可略))
#🌟不包含終止值

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8, 9. , 9.2, 9.4, 9.6, 9.8])

## 5. 超重要 `axis` 觀念

初學 `numpy` 很多人有點弄不清楚 `axis` 概念。其實掌握矩陣, 或很像矩陣的陣列都是「先列後行」就可以!

我們先弄個 array 來練習。

In [90]:
A = np.arange(10).reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 【重點】 一列一列算下來是 `axis=0`

![axis=0](images/axis0.png)

In [91]:
A.sum(axis=0)

array([ 5,  7,  9, 11, 13])

### 【重點】 一行一行算過去是 `axis=1`

![axis=1](images/axis1.png)

In [92]:
A.sum(axis=1)

array([10, 35])

### 【提示】當然也有可能全部算

In [93]:
A.sum()

45

## 6. array 過濾器

篩出我們要的資料, 這樣的技巧非常重要!

### 【例子】篩出大於 0 的數

我們有個陣列, 想找出大於 0 的數。<br>
L = np.array([3, -2, -1, 5, 7, -3])

In [106]:
L = np.array([3, -2, -1, 5, 7, -3])

我們可以很白痴的自己判斷...<br>
c = np.array([True,False,False,True,True,False])

In [107]:
c = np.array([True,False,False,True,True,False]) #T F需大寫

這是做啥呢? 我們可以瞬間...

In [108]:
L[c] #[放篩選條件]

array([3, 5, 7])

除了自己做很白痴, 這看來很厲害!

事實上我們可以叫 `numpy` 做!

In [109]:
L>0

array([ True, False, False,  True,  True, False])

這有點強, 我們還可以一次到位!

In [111]:
L[L > 0] #都沒有改變原始值 因為沒有'=''(assign)

array([3, 5, 7])

In [112]:
L = L[L>0] #有'=', 會改變原始值
L

array([3, 5, 7])

## 7. 次元切割刀

`numpy` 中 array 的切割法和 list 很像。

In [134]:
x = np.arange(10) #np.arange陣列以等差數列的形式產生，指定間隔
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
#-----1維陣列切法#-----
#Q: get 3-6?
x[3:7] #不包含終止值

array([3, 4, 5, 6])

### 【技巧】2維陣列切法

記得先列後行!

In [139]:
x.shape=(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

要所有的row, 切出行 1-3 位置。

In [138]:
x[:,1:3]

array([[1, 2],
       [6, 7]])

要所有的行col, 切出第 1 列row!

In [140]:
x[1,:]

array([5, 6, 7, 8, 9])

## 8. `NumPy` 的 `zip` 和 `unzip`

之前我們介紹 list 可以用 `zip` 和 `unzip` (其實還是 `zip`) 做到的資料格式變換, 在 array 中怎麼做呢?

![zip and unzip](images/zip.png)

### 【重點】array 的 `zip`

![array zip](images/arrzip.png)

In [157]:
#zip拉鍊 把兩分開的東西鍊起來
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

In [158]:
A = np.c_[x,y] #row轉成col #要用[]
A

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [159]:
B = np.r_[x,y] #兩row合併
B

array([1, 2, 3, 4, 5, 6, 7, 8])

### 【重點】array 的 `unzip`

這裡其實只需要用到 array 的切割法...

![array zip](images/arrunzip.png)

In [161]:
#🌟[]取
A[:,0]

array([1, 2, 3, 4])

In [162]:
A[:,1]

array([5, 6, 7, 8])